# Generated by Django 5.2.3 on 2025-06-30 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(editable=False, max_length=11, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'cart_code')},
        ),
    ]
